### ISSUE TITLE
java.lang.NoSuchMethodError 

### ISSUE THREAD

**Issue by tushar-ahmed** [Dulab2020/AutoVEM#1]
Hello there,

_First of all, thank you for developing a wonderful tool. However, I need some help regarding this because I'm not being able to use it._ 
_I tried to run it on your given sample. I used the command as follows:_

python3 main.py auto --input /home/shishir/AutoVEM/samples/input/genome_sequence --sites 241 3037 14408 23403 26144 28144 --frequency 0.01 --output test

_then sequences are aligned, SNVs are identified and all. But the error occurs while using Haploview.jar tool as follows._

Have successfully obtained SNV mutations information.
Dealing with snp sites...
241
3037
14408
23403
28144
Done!
Obtaining data.tsv file...
Done!
Obtaining block.txt file...
Done!
Obtaining map file...
Done!
Obtaining snp.ped file...
Done!
Linkage analyzing...
*****************************************************
Haploview 4.2	Java Version: 11.0.9.1
*****************************************************

Arguments:	-n	-skipcheck	-pedfile	/home/shishir/AutoVEM/test/snp.ped	-info	/home/shishir/AutoVEM/test/snp.info	-blocks	/home/shishir/AutoVEM/test/block.txt	-png	-out	/home/shishir/AutoVEM/test/plot	

Skipping genotype file check
Using data file: /home/shishir/AutoVEM/test/snp.ped
Using output fileroot: /home/shishir/AutoVEM/test/plot
Using marker information file: /home/shishir/AutoVEM/test/snp.info
Writing output to plot.CUSTblocks
Using custom blocks file: /home/shishir/AutoVEM/test/block.txt
Writing output to plot.LD.PNG
Exception in thread "main" java.lang.NoSuchMethodError: 'void java.lang.System.runFinalizersOnExit(boolean)'
	at com.sun.jimi.core.Jimi.<clinit>(Jimi.java:128)
	at edu.mit.wi.haploview.HaploText.processFile(HaploText.java:1680)
	at edu.mit.wi.haploview.HaploText.processTextOnly(HaploText.java:1369)
	at edu.mit.wi.haploview.HaploText.<init>(HaploText.java:245)
	at edu.mit.wi.haploview.HaploView.main(HaploView.java:1600)
Done!
Haplotyping......
Done!
Plotting...
Traceback (most recent call last):
  File "main.py", line 954, in <module>
    module2(snpFile, outputDirectory, sites, frequency)
  File "main.py", line 908, in module2
    plot(data_plot, haplotypes, directory)
  File "main.py", line 633, in plot
    record = 'other' + '\t' + 'NA' + '\t' + str(Fre_dict['other'])
KeyError: 'other'

_I'm not getting the problem. One thing I noticed is that snp.ped is not generated although it is shown obtained above. 
I manually tried to run the Haploview tool using your command and got the following error:_ 

java -jar -n -skipcheck -pedfile /home/shishir/AutoVEM/test/snp.ped -info /home/shishir/AutoVEM/test/snp.info -blocks /home/shishir/AutoVEM/test/block.txt -png -out /home/shishir/AutoVEM/test/plot 
Error: Unable to access jarfile /home/shishir/AutoVEM/test/snp.ped

**Java version:**
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

Please suggest me what to do.
Thank you

**Comment by Dulab2020** [comment]
Hello tushar-ahmed,
Thank you for using AutoVEM. Some other tools are used in AutoVEM, so the operating environment of the software may be a little bit complicated.

About the first question, I think it may be caused by unsuitable JAVA environment. I suggest you reinstall your JRE according to this websites. https://www.broadinstitute.org/haploview/tutorial.

About the second question, I noticed that you didn't input the Haploview.jar file after -jar command, and might lead the error. 
 java -jar Haploview.jar -n -skipcheck -pedfile /home/shishir/AutoVEM/test/snp.ped -info /home/shishir/AutoVEM/test/snp.info -blocks /home/shishir/AutoVEM/test/block.txt -png -out /home/shishir/AutoVEM/test/plot

Finally, it is recommended that the output folder be an empty folder. We find the previous sample is not very appropriate. New sample is provided. 

If you have any other questions, please do not hesitate to contact us. 

Thanks again. 
Best regards, Bin and Hongli

**Comment by tushar-ahmed** [comment]
Thank you very much for your quick response.

According to your suggestions, I have reinstalled JRE but still facing the same problem.

*****************************************************
Haploview 4.2	Java Version: 15.0.2
*****************************************************

Then I manually ran the haploview this time correctly and the problem found is snp.ped file is not generated during the process. 

**here is the output:** 

shishir@D3W:~/AutoVEM$  java -jar tools/Haploview.jar -n -skipcheck -pedfile /home/shishir/AutoVEM/test/snp.ped -info /home/shishir/AutoVEM/test/snp.info -blocks /home/shishir/AutoVEM/test/block.txt -png -out /home/shishir/AutoVEM/test/plot 
*****************************************************
Haploview 4.2	Java Version: 15.0.2
*****************************************************

Arguments:	-n	-skipcheck	-pedfile	/home/shishir/AutoVEM/test/snp.ped	-info	/home/shishir/AutoVEM/test/snp.info	-blocks	/home/shishir/AutoVEM/test/block.txt	-png	-out	/home/shishir/AutoVEM/test/plot	

Skipping genotype file check
Using data file: /home/shishir/AutoVEM/test/snp.ped
Using output fileroot: /home/shishir/AutoVEM/test/plot
Genotype file is empty or nonexistent: snp.ped

Thank you in advance

**Comment by Dulab2020** [comment]
Thank you for your feedback.

When uploading the sample for the first time, we just wanted to show the format of the software input files, and did not consider that users might use these files for testing. In the previous sample, there are too little sequences. So it may not be suitable for testing. We are very sorry about this.

New example was uploaded. There are about 1500 genome sequences. We tested the tool with new example and it woked well. We used the command as follows:
python main.py auto --input /home/AutoVEM/genome_sequences/ --output /home/AutoVEM/outDir
The program took less than 15 minutes. You can test AutoVEM with the new example.

In addition, we also updated the program source code. If the JRE meets the requirements of Haploview tool, the software should be able to run normally. You can use snp.ped, snp.info and block.txt files in the samples\output directory to test if Java Runtime Environment meets the requirements of Haploview tool.

Thinks again and We are continuously improving the tool.
Best regards, Bin and Hongli

**Comment by tushar-ahmed** [comment]
It worked! 

Thank you so much for your continuous support!
